include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - unawaited_futures
    - await_only_futures
    - always_declare_return_types
    - cancel_subscriptions
